import type { CustomerRecord, TreatmentPerformance } from './types';

/**
 * Deterministic business calculations over clinic records.
 *
 * These are kept pure and free of I/O so the AI layer can call them as tools and
 * the numbers stay verifiable in tests rather than being generated by a model.
 */

/** Rounds to `places` decimals, avoiding floating point noise in output. */
function round(value: number, places = 4): number {
  const factor = 10 ** places;
  return Math.round(value * factor) / factor;
}

/** Share of consultations that resulted in a purchase. Returns 0 for an empty set. */
export function conversionRate(records: CustomerRecord[]): number {
  if (records.length === 0) return 0;
  const purchased = records.filter((r) => r.status === 'purchased').length;
  return round(purchased / records.length);
}

/** Share of purchasing customers who rebooked. Denominator is purchases, not all visits. */
export function rebookingRate(records: CustomerRecord[]): number {
  const purchases = records.filter((r) => r.status === 'purchased');
  if (purchases.length === 0) return 0;
  return round(purchases.filter((r) => r.rebooked).length / purchases.length);
}

/** Mean spend across purchasing customers only, so declines don't dilute the figure. */
export function averageSpend(records: CustomerRecord[]): number {
  const purchases = records.filter((r) => r.status === 'purchased');
  if (purchases.length === 0) return 0;
  const total = purchases.reduce((sum, r) => sum + r.amountSpent, 0);
  return round(total / purchases.length, 2);
}

/** Total revenue represented by these records. */
export function totalRevenue(records: CustomerRecord[]): number {
  return round(
    records.reduce((sum, r) => sum + r.amountSpent, 0),
    2,
  );
}

/** Mean satisfaction, ignoring customers who left no rating. Null when nobody rated. */
export function averageSatisfaction(records: CustomerRecord[]): number | null {
  const rated = records.filter((r) => r.satisfaction !== null);
  if (rated.length === 0) return null;
  const total = rated.reduce((sum, r) => sum + (r.satisfaction as number), 0);
  return round(total / rated.length, 2);
}

/**
 * Customers whose last visit falls within `days` of `asOf`.
 * Used for "who hasn't returned recently" style questions.
 */
export function lapsedCustomers(
  records: CustomerRecord[],
  days: number,
  asOf: Date = new Date(),
): CustomerRecord[] {
  const cutoff = asOf.getTime() - days * 24 * 60 * 60 * 1000;
  return records.filter((r) => new Date(r.lastVisit).getTime() < cutoff);
}

/** Share of customers still active within the window. */
export function retentionRate(
  records: CustomerRecord[],
  days: number,
  asOf: Date = new Date(),
): number {
  if (records.length === 0) return 0;
  const lapsed = lapsedCustomers(records, days, asOf).length;
  return round((records.length - lapsed) / records.length);
}

/** Groups records by a field, for per-treatment or per-provider comparisons. */
export function groupBy<K extends keyof CustomerRecord>(
  records: CustomerRecord[],
  field: K,
): Map<string, CustomerRecord[]> {
  const groups = new Map<string, CustomerRecord[]>();
  for (const record of records) {
    const key = String(record[field]);
    const bucket = groups.get(key);
    if (bucket) bucket.push(record);
    else groups.set(key, [record]);
  }
  return groups;
}

/**
 * Per-treatment breakdown, sorted worst-converting first so the weakest area
 * surfaces without the caller having to sort.
 */
export function treatmentPerformance(records: CustomerRecord[]): TreatmentPerformance[] {
  return [...groupBy(records, 'treatment').entries()]
    .map(([treatment, group]) => ({
      treatment,
      consultations: group.length,
      conversionRate: conversionRate(group),
      rebookingRate: rebookingRate(group),
      averageSpend: averageSpend(group),
      averageSatisfaction: averageSatisfaction(group),
    }))
    .sort((a, b) => a.conversionRate - b.conversionRate);
}

/** Per-provider conversion, weakest first. Answers "which provider needs attention". */
export function providerPerformance(records: CustomerRecord[]): TreatmentPerformance[] {
  return [...groupBy(records, 'provider').entries()]
    .map(([provider, group]) => ({
      treatment: provider,
      consultations: group.length,
      conversionRate: conversionRate(group),
      rebookingRate: rebookingRate(group),
      averageSpend: averageSpend(group),
      averageSatisfaction: averageSatisfaction(group),
    }))
    .sort((a, b) => a.conversionRate - b.conversionRate);
}
